# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- cj

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: PowerShell@2
  displayName: CodeQL Setup
  inputs:
    targetType: inline
    script: |     
      Write-Host "DOWNLOADING CODEQL WINDOWS BUNDLE"
      cd $(Agent.WorkFolder)
      Invoke-WebRequest -uri https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-win64.tar.gz -OutFile $(OurWorkingDirectoryV2)\codeql-bundle-win64.tar.gz
      tar zxf ./codeql-bundle-win64.tar.gz
- task: PowerShell@2
  displayName: CodeQL Initialisation
  inputs:
    targetType: inline
    script: |
      Write-Host "CREATING CODEQL DATABASE"    
      & $(Agent.WorkFolder)\codeql\codeql database create $(OurWorkingDirectoryV2)\codeql-database --language=csharp 
      #--command=
      #dotnet restore **/*.sln
      #dotnet build **/something.csproj --configuration $(BuildConfiguration) --no-restore

