# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- cj

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  #buildPlatform: 'Any CPU'
  #buildConfiguration: 'Release'

steps:

- task: PowerShell@2
  displayName: CodeQL Setup
  inputs:
    targetType: inline
    script: |     
      Write-Host "DOWNLOADING CODEQL WINDOWS BUNDLE"
      mkdir codeql
      cd codeql
      wget https://github.com/github/codeql-action/releases/download/codeql-bundle-20210421/codeql-bundle-win64.tar.gz -outfile "codeql-bundle-win64.tar.gz"
      tar zxf .\codeql-bundle-win64.tar.gz codeql
- task: PowerShell@2
  displayName: CodeQL Initialisation
  inputs:
    targetType: inline
    script: |
      Write-Host "CREATING CODEQL DATABASE"    
      & codeql\codeql\codeql database create $(Agent.WorkFolder)\codeql-database --language=csharp 
      #--command=
      #dotnet restore **/*.sln
      #dotnet build **/something.csproj --configuration $(BuildConfiguration) --no-restore

- task: PowerShell@2
  displayName: CodeQL Analysis
  inputs:
    targetType: inline
    script: |
      Write-host "PERFORMING CODEQL ANALYSIS"
      New-Item -ItemType "directory" -Path $(Agent.WorkFolder)\codeql-sarif
      New-Item -ItemType "directory" -Path $(Agent.WorkFolder)\codeql-sarif\code-scanning-alerts.sarif
    
      & codeql\codeql\codeql database analyze $(Agent.WorkFolder)\codeql-database $(Agent.WorkFolder)\codeql\qlpacks\codeql-csharp\codeql-suites\csharp-code-scanning.qls --format=sarif-latest --output=$(Agent.WorkFolder)\codeql-sarif\code-scanning-alerts.sarif
